### ISSUE TITLE
CORS - Textures and Tained canvas

### ISSUE THREAD

**Issue by kubaracek** [joakin/elm-canvas#12]
Problem
---
Images downloaded as textures seems not to use `crossOrigin = "Anonymous"` flag and they make my canvas tained.

Reproduce
---

I've created this Ellie (https://ellie-app.com/86XKmYD9Mxya1) that loads a texture, just popup the browser console and execute this

```javascript
var tmpCtx=document.createElement("canvas").getContext("2d");
tmpCtx.drawImage(document.querySelectorAll("img[src='https://www.alsipnursery.com/wp-content/uploads/2019/04/1703190.jpg']")[0],0,0);
tmpCtx.getImageData(1,1,1,1);
```

You can see that on my project https://kubaracek.github.io/hanggliding-map/ that uses map tiles

```javascript
var tmpCtx=document.createElement("canvas").getContext("2d");
tmpCtx.drawImage(document.querySelectorAll("img[src='https://tile.nextzen.org/tilezen/terrain/v1/256/terrarium/11/1087/715.png?api_key=Nl9_q6yZQA6NIJp6Zn9kYg']")[0],0,0);
tmpCtx.getImageData(1,1,1,1);
```

Interesting this is that on my project the image returns: `access-control-allow-origin: *`

**Comment by joakin** [comment]
Loading the image works fine, see: https://ellie-app.com/88GsjVC9q3Fa1

It is when you try and manipulate the canvas that the browser complains because it has mixed with CORS data.

I'll have a look at the PR and look into the docs for the `crossorigin` attribute on HTML elements and if it doesn't have any negative impact we can merge it.

**Comment by joakin** [comment]
Closing this, we can continue conversation on the PR. Thanks @kubaracek
