### ISSUE TITLE
Support for "groups" or similar batching of settings to multiple `Renderable`

### ISSUE THREAD

**Issue by SiriusStarr** [joakin/elm-canvas#33]
(Per discussion on Slack.)

Currently there are no functions along the lines of `group : List Setting -> List Renderable -> Renderable`.  As such, if one has e.g. a standard transformation, there is no way to apply it to all (or some) of one's `Renderable`s, rather than having to apply it to each individually.

While the canvas API does not natively support groups, it is a common feature in many other interfaces to it, as well as e.g. `elm-playground`.

**Comment by joakin** [comment]
This conversation has happened enough times that I think it warrants implementing it.

Ideally it can be done at the elm layer, and leverage context pushing and popping for it, so that the JS library doesn't need updating

**Comment by joakin** [comment]
I've built the feature but because I had to move a type to an internal module and expose an alias instead (to have the recursive type for the group), it will be a major version change. I'll have to review if there are other things I should bundle on it and any docs I need to update before publishing a release.

**Comment by joakin** [comment]
Re-opening, will close on release

**Comment by joakin** [comment]
Published 5.0.0 with the group function https://package.elm-lang.org/packages/joakin/elm-canvas/5.0.0/

Let me know if it works for you or if you encounter any issues!
