### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by linsyking** [joakin/elm-canvas#36]
I tested your code and examples, but nothing shows up.

Is this repo still maintained?

**Comment by joakin** [comment]
Can you be more specific? Any compiler error messages? Any console error
messages? How did you “test” it?

Things should work AFAICT

**Comment by auryn31** [comment]
I had the same issue, until i included the `js` file. Totally missed that

`<script src="<script src="https://unpkg.com/elm-canvas@2.2.4/elm-canvas.js"></script>"></script>`

**Comment by joakin** [comment]
elm-canvas requires a JS library like is mentioned everywhere, so if you want to compile things you will need to set things up to use a custom html file because neither the elm compiler html output nor the reactor support custom HTML.

I compile the library and examples using the makefile https://github.com/joakin/elm-canvas/blob/master/Makefile

When I make a new example I make an Elm file in examples/ and HTML file in public/ and then run `make` or `make dist`, and open the HTML file in the browser.

Also, the examples are self contained so feel free to use the sketch repo or the Ellie and copy paste the elm file of the example you want to try. See https://github.com/joakin/elm-canvas#usage



I’m closing this issue because the original poster didn’t provide any detail neither on the title or description of it. @auryn31 feel free to open any new issues if you have any problems :)
