### ISSUE TITLE
Support for HiDPI?

### ISSUE THREAD

**Issue by HappMacDonald** [joakin/elm-canvas#5]
I find that rendering text on a hidpi screen (in my case, just Windows 10 Chrome with interface set to 175%)  is very blurry. I have read here:

https://www.html5rocks.com/en/tutorials/canvas/hidpi

and here:

https://groups.google.com/forum/#!topic/elm-discuss/pq1KS8XgFiQ

that this could be addressed by a few lines of JS trickery.

Any chance of some kind of support for that here? 

It looks like the trick that they use is a drop-in option that shouldn't disturb any existing code that uses canvas and should still look perfect on non-HiDPI screens. :o

**Comment by joakin** [comment]
Oh I didn't notice this! Thanks for the links and the research.

I think this is something we can definitely address in the library. I'm going to keep it open to look into it before releasing the new version (which is quite different from the published one).

I think we will do something like what they ended up in [src/Native/Graphics/Collage.js#L296-L301](https://github.com/elm/core/blob/c8f7c86caa16cd85f0ad8ca304512044b2ee2406/src/Native/Graphics/Collage.js#L296-L301).

For now, you can work around it, which is great, but involves some setup work. You can pass the devicePixelRatio as a Flag to the program, and then set the style width and height to the size you want and the attributes width and height to those dimensions multiplied by the pixel ratio. Something like

```elm
    [ width (w * pixelRatio)
    , height (h * pixelRatio)
    , style "width" (String.fromInt w ++ "px")
    , style "height" (String.fromInt h ++ "px")
    ]
```

As the attributes for the element.

I think this should be automatic though, so something to work on. Not sure if it is easiest to handle on the web component directly, will see.

**Comment by joakin** [comment]
I've added a fix to the elm-canvas npm package and published 2.1.0, it seems to work well 👍 see  https://chimeces.com/elm-canvas/cubic-disarray.html for example

**Comment by HappMacDonald** [comment]
Hmm now that 3.0.0 is out, are there any up to date examples to work from?

My previous code complains of things like "CanvasColor stopped existing" and "what's a Canvas.command?"

**Comment by joakin** [comment]
Hi Jesse.

All examples in [examples/](
https://github.com/joakin/elm-canvas/tree/master/examples) are up to date
and working.

The setup in the HTML is the same, just ensure you are loading the 2.1 web
component if you want the HiDpi fix.

The examples may be a bit complex to parse so I would recommend having a
look at [NewApiTest.elm](
https://github.com/joakin/elm-canvas/blob/master/examples/NewApiTest.elm)for
a small summary one.

I also spent a lot of effort writing the docs for the package site
([Canvas](
https://package.elm-lang.org/packages/joakin/elm-canvas/3.0.0/Canvas)). I
think if you spend 10 minutes reading through I would appreciate any
feedback on things that don’t make sense.

V3 is a more high level version than v2, less DOM like and more elm-like.
You don’t need to worry about the settings affecting things globally, and
other canvas inconveniences. I would love if you try it and find it
convenient to migrate, as I do think it is better, but keep in mind that v2
is there and working fine so also feel free to stick with it if it works
well for you and you don’t want to bother. The hidpi fixes work for v2 too.

Looking forward to any feedback. I’d also love to know what you are using
it for, since I want to write something up at some point and I’d like to
emphasize use cases or pros of this approach versus svg or webgl.

**Comment by joakin** [comment]
Hi Jesse.

All examples in [examples/](https://github.com/joakin/elm-canvas/tree/master/examples) are up to date and working.

The setup in the HTML is the same, just ensure you are loading the 2.1 web component if you want the HiDpi fix.

The examples may be a bit complex to parse so I would recommend having a look at [NewApiTest.elm](https://github.com/joakin/elm-canvas/blob/master/examples/NewApiTest.elm)for a small summary one.

I also spent a lot of effort writing the docs for the package site ([Canvas](https://package.elm-lang.org/packages/joakin/elm-canvas/3.0.0/Canvas)). I think if you spend 10 minutes reading through you will see what the new version is about, I would appreciate any feedback on things that don’t make sense.

V3 is a more high level version than v2, less DOM like and more elm-like. You don’t need to worry about the settings affecting things globally, and other canvas inconveniences. I would love if you try it and find it convenient to migrate, as I do think it is better, but keep in mind that v2 is there and working fine so also feel free to stick with it if it works well for you and you don’t want to bother. The hidpi fixes work for v2 too.

Looking forward to any feedback. I’d also love to know what you are using it for, since I want to write something up at some point and I’d like to emphasize use cases or pros of this approach versus svg or webgl.

**Comment by joakin** [comment]
I’ve opened #6 to track better documenting how to get Color and what it is, since that may be confusing
